#!/usr/bin/bash

#compile
g++ assignment_2.cpp -o assignment_2

#generic run statement
./assignment_2 route_summary ./data/04_June_Route1.txt
./assignment_2 route_summary ./data/01_June10_morning_Route1.txt
./assignment_2 route_summary ./data/02_June10_Route1.txt
./assignment_2 route_summary ./data/03_June10_AllRoutes.txt
./assignment_2 route_summary ./data/04_June_Route1.txt
./assignment_2 route_summary ./data/05_July_Route1.txt
./assignment_2 route_summary ./data/06_August_Route1.txt
./assignment_2 route_summary ./data/07_June_AllRoutes.txt
./assignment_2 route_summary ./data/08_JanFebMar_Route1.txt
./assignment_2 route_summary ./data/09_JuneJulyAug_AllRoutes.txt
./assignment_2 route_summary ./data/10_Sept2017_Aug2022_AllRoutes.txt
./assignment_2 route_summary ./data/11_ShortLineI.txt
./assignment_2 route_summary ./data/14_EmptyFieldI.txt
./assignment_2 route_summary ./data/15_EmptyFieldII.txt
./assignment_2 route_summary ./data/16_EmptyFieldIII.txt
./assignment_2 route_summary ./data/17_NonNumericI.txt
./assignment_2 route_summary ./data/18_NonNumericII.txt
./assignment_2 route_summary ./data/19_BadTimeI.txt
./assignment_2 route_summary ./data/20_BadTimeII.txt

rm assignment_2
