#!/usr/bin/bash

#compile
g++ assignment_2.cpp -o assignment_2

#generic run statement
# ./assignment_2 route_summary ./data/04_June_Route1.txt
./assignment_2 days ./data/04_June_Route1.txt

rm assignment_2
